module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./public/index.html",
  ],
  theme: {
    extend: {
      colors: {
        background: "#060e20",
        "on-background": "#dee5ff",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#ae8dff",
        "on-tertiary-fixed-variant": "#553777",
        "on-secondary-fixed-variant": "#004da8",
        "on-tertiary-fixed": "#361757",
        "surface-container": "#0f1930",
        "inverse-surface": "#faf8ff",
        "surface-container-low": "#091328",
        surface: "#060e20",
        "secondary-container": "#005ac2",
        "on-primary-fixed-variant": "#370086",
        "on-primary-fixed": "#000000",
        "surface-dim": "#060e20",
        "primary-dim": "#8455ef",
        "secondary-dim": "#699cff",
        "on-surface": "#dee5ff",
        "on-primary-container": "#2b006e",
        "outline-variant": "#40485d",
        "inverse-on-surface": "#4d556b",
        "surface-container-high": "#141f38",
        "tertiary-fixed": "#d6b2fc",
        outline: "#6d758c",
        "secondary-fixed-dim": "#a9c4ff",
        "secondary-fixed": "#bfd1ff",
        "on-primary": "#39008c",
        "on-surface-variant": "#a3aac4",
        "on-error-container": "#ffb2b9",
        "surface-container-highest": "#192540",
        "tertiary-fixed-dim": "#c8a5ed",
        secondary: "#699cff",
        "primary-fixed-dim": "#a27cff",
        "on-tertiary": "#553777",
        "tertiary-dim": "#c8a5ed",
        "surface-bright": "#1f2b49",
        "surface-tint": "#ba9eff",
        "inverse-primary": "#6e3bd7",
        error: "#ff6e84",
        "primary-container": "#ae8dff",
        "on-tertiary-container": "#4c2e6d",
        "on-secondary-fixed": "#003271",
        "error-container": "#a70138",
        tertiary: "#e1c3ff",
        "on-secondary": "#001e4a",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        glow: "0 25px 60px rgba(186, 158, 255, 0.15)",
      },
    },
  },
  plugins: [],
};
